# Generated by Django 5.0 on 2026-09-29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import packing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inner_length', models.DecimalField(decimal_places=2, help_text='Internal length in cm (must be > 0)', max_digits=10, validators=[packing.models.validate_strictly_positive])),
                ('inner_width', models.DecimalField(decimal_places=2, help_text='Internal width in cm (must be > 0)', max_digits=10, validators=[packing.models.validate_strictly_positive])),
                ('inner_height', models.DecimalField(decimal_places=2, help_text='Internal height in cm (must be > 0)', max_digits=10, validators=[packing.models.validate_strictly_positive])),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum allowed weight in grams (must be > 0)', max_digits=10, validators=[packing.models.validate_strictly_positive])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Box procurement/shipping cost (must be >= 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name_plural': 'Boxes',
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in cm (must be > 0)', max_digits=10, validators=[packing.models.validate_strictly_positive])),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in cm (must be > 0)', max_digits=10, validators=[packing.models.validate_strictly_positive])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm (must be > 0)', max_digits=10, validators=[packing.models.validate_strictly_positive])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in grams (must be > 0)', max_digits=10, validators=[packing.models.validate_strictly_positive])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity must be at least 1', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='packing.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
